version: '3.1'
services:

  # Frontend container - serving static files
  frontend:
    image: 'nginx:alpine'
    working_dir: /frontend
    volumes:
      - './app:/app'
      - './conf/nginx.conf:/etc/nginx/conf.d/default.conf'  # Frontend Nginx config
    ports:
      - '1235:80'
