version: '3.1'
services:
  # MySQL service for the backend
  mysql:
    image: 'mysql:8.0'
    volumes:
      - '../mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=webshop
      - MYSQL_USER=databaseuser
      - MYSQL_PASSWORD=databasepassword
    ports:
      - '1236:3306'
    networks:
      - backend

  # Frontend container - serving static files
  frontend:
    image: 'nginx:alpine'
    working_dir: /frontend
    volumes:
      - '../app/frontend:/frontend'
      - './frontend/nginx.conf:/etc/nginx/conf.d/default.conf'  # Frontend Nginx config
    ports:
      - '1234:80'

  # Backend container - serving API and business logic
  backend:
    image: 'nginx:alpine'
    working_dir: /backend
    volumes:
      - '../app/backend:/backend'
      - './backend/nginx.conf:/etc/nginx/conf.d/default.conf'  # Backend Nginx config
    ports:
      - '1235:80'
    depends_on:
      - php-fpm-backend
      - mysql
    networks:
      - backend

  # PHP-FPM for handling backend-PHP requests
  php-fpm-backend:
    build: phpdocker/php-fpm
    working_dir: /backend
    volumes:
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
      - '../app/backend:/backend'
    expose:
      - "9000"
    networks:
      - backend

  # PHPMyAdmin for MySQL administration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - '1237:80'
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge