version: '3.1'

services:
  cert-gen:
    image: ubuntu:latest
    container_name: mkcert_container
    volumes:
      - ./certs:/certs  # Mount volume to store the generated certificates
    working_dir: /certs
    command: /bin/bash -c "apt-get update && apt-get install -y curl libnss3-tools && \
      curl -JLO https://dl.filippo.io/mkcert/latest?for=linux/amd64 && \
      chmod +x mkcert-v*-linux-amd64 && mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert && \
      mkcert -install && mkcert superhappy.local"
